database:
  host: localhost
  port: 5432
  user: postgres
  password: class
  dbname: banner_service_db

server:
  port: 8080

jwt:
  secret: akdj2374529asdfbalsjfb3
  expiration_hours: 24
